FROM python:2.7
MAINTAINER Lucas Waye <lucas@lucaswaye.com>

# Thrift-specific
ENV THRIFT_VERSION 0.9.3
RUN buildDeps=" \
		automake \
		bison \
		curl \
		flex \
		g++ \
		libboost-dev \
		libboost-filesystem-dev \
		libboost-program-options-dev \
		libboost-system-dev \
		libboost-test-dev \
		libevent-dev \
		libssl-dev \
		libtool \
		make \
		pkg-config \
	"; \
	apt-get update && apt-get install -y --no-install-recommends $buildDeps && rm -rf /var/lib/apt/lists/* \
	&& curl -sSL "http://apache.mirrors.spacedump.net/thrift/$THRIFT_VERSION/thrift-$THRIFT_VERSION.tar.gz" -o thrift.tar.gz \
	&& mkdir -p /usr/src/thrift \
	&& tar zxf thrift.tar.gz -C /usr/src/thrift --strip-components=1 \
	&& rm thrift.tar.gz \
	&& cd /usr/src/thrift \
	&& ./configure  --without-tests --without-python --with-cpp \
	&& make \
	&& make install \
	&& cd / \
	&& rm -rf /usr/src/thrift

# Whip-specific
WORKDIR /whip

COPY src/adapter/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY src src
RUN src/adapter/update-stubs.sh \
	&& src/adapter/regen-parser.sh

RUN cd /whip/src/shim/linux \
	&& make

ENV PATH "$PATH:/whip/src/bin"
VOLUME /whip

