/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef clientprotocol_CONSTANTS_H
#define clientprotocol_CONSTANTS_H

#include "clientprotocol_types.h"

namespace ClientProxy {

class clientprotocolConstants {
 public:
  clientprotocolConstants();

};

extern const clientprotocolConstants g_clientprotocol_constants;

} // namespace

#endif
