/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "clientprotocol_constants.h"

namespace ClientProxy {

const clientprotocolConstants g_clientprotocol_constants;

clientprotocolConstants::clientprotocolConstants() {
}

} // namespace

