version: '3'
services:
  parse_results:
    build: ./parse_results
    volumes:
      - ./results:/results
  chess:
    build: ./chess
    depends_on:
      - parse_results
    environment:
      NUM_OPS: ${NUM_OPS}
    volumes:
      - ./results:/results
  twitter:
    build: ./twitter
    depends_on:
      - parse_results
    environment:
      NUM_OPS: ${NUM_OPS}
    volumes:
      - ./results:/results
  evernote:
    build: ./evernote
    depends_on:
      - parse_results
    environment:
      NUM_OPS: ${NUM_OPS}
    volumes:
      - ./results:/results
